# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNQiniuUploader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNQiniuUploader
  pod "Qiniu", "~> 7.1.5"
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

end
